- name: myapp
  type: 'php:8.3'
  source:
    root: app
  web:
    locations:
      '/':
        root: "webroot"
        passthru: "/index.php"
  hooks:
    build: |
      composer install
  mounts:
    'tmp':
      source: tmp
      source_path: files/tmp
    'logs':
      source: tmp
      source_path: files/logs